# Generated by Django 5.1.1 on 2024-09-10 15:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("empleados", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TipoNovedadModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Tipo_novedad", models.TextField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="NovedadesModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombres_empleado", models.TextField(max_length=200)),
                ("apellidos_empleado", models.TextField(max_length=200)),
                ("Fecha_inicio", models.DateField()),
                ("Fecha_fin", models.DateField()),
                ("soporte", models.FileField(upload_to="soportes/")),
                (
                    "iden",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="iden",
                        to="empleados.empleadosmodels",
                    ),
                ),
                (
                    "novedad_empleado",
                    models.ForeignKey(
                        default=1,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="novedades.tiponovedadmodel",
                    ),
                ),
            ],
        ),
    ]
