# Generated by Django 5.1.1 on 2024-09-10 15:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="RolModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("roles", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="EmpleadosModels",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombres_empleado", models.CharField(max_length=200)),
                ("apellidos_empleado", models.CharField(max_length=200)),
                ("identificacion", models.IntegerField(unique=True)),
                (
                    "sexo_empleado",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                ("telefono_empleado", models.CharField(max_length=10)),
                ("direccion_empleado", models.CharField(max_length=50)),
                ("email_empleado", models.EmailField(max_length=254, unique=True)),
                ("cargo_empleado", models.CharField(max_length=200)),
                (
                    "salario_empleado",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                ("contacto_emergencia", models.CharField(max_length=200)),
                ("tel_emergencia", models.CharField(max_length=10)),
                (
                    "foto_empleado",
                    models.ImageField(
                        blank=True,
                        default="fotos_empleados/default.png",
                        null=True,
                        upload_to="fotos_empleados/",
                    ),
                ),
                (
                    "rol_empleado",
                    models.ForeignKey(
                        default=1,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="empleados.rolmodel",
                    ),
                ),
            ],
        ),
    ]
